include:
- ./backend/extract/extract.py
kind: ArchiveUploadSpec
name: backend-extract-extract-py-2eMM

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: extract-8dffb4db-2f7c-4c67-a7f4-82b2c00b1b23
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://backend-extract-extract-py-2eMM
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T07:58:53Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: extract
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: extract-8dffb4db-2f7c-4c67-a7f4-82b2c00b1b23
      namespace: ""
  requestsPerPod: 1
  resources: {}
