include:
- ./functions/getlocations.zip
kind: ArchiveUploadSpec
name: functions-getlocations-zip-LmvU

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getlocations
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-getlocations-zip-LmvU
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-09T08:40:30Z"
