include:
- ./functions/getweather.zip
kind: ArchiveUploadSpec
name: functions-getweather-zip-rzvp

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getweather
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-getweather-zip-rzvp
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-09T00:50:22Z"
