include:
- ./functions/getroadcondition.zip
kind: ArchiveUploadSpec
name: functions-getroadcondition-zip-QhJM

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getroadcondition
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-getroadcondition-zip-QhJM
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-09T08:54:38Z"
