include:
- ./functions/search.zip
kind: ArchiveUploadSpec
name: functions-search-zip-2Ggt

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-search-zip-2Ggt
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-09T08:40:47Z"
