include:
- ./functions/put.zip
kind: ArchiveUploadSpec
name: functions-put-zip-PEuj

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: put
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-put-zip-PEuj
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-10T11:17:22Z"

---
include:
- ./functions/put.zip
kind: ArchiveUploadSpec
name: functions-put-zip-gfHz
