include:
- ./functions/searchweather.zip
kind: ArchiveUploadSpec
name: functions-searchweather-zip-fgjt

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: searchweather
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-searchweather-zip-fgjt
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-11T07:34:40Z"
