include:
- ./backend/put.zip
kind: ArchiveUploadSpec
name: backend-put-zip-8mJs

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: put
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-put-zip-8mJs
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T06:06:47Z"
