include:
- ./backend/search.zip
kind: ArchiveUploadSpec
name: backend-search-zip-4Odl

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: search
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-search-zip-4Odl
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-21T08:16:06Z"
