include:
- ./functions/searchweather.zip
kind: ArchiveUploadSpec
name: functions-searchweather-zip-sgQL

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: searchweather
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-searchweather-zip-sgQL
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T06:50:19Z"
