include:
- ./backend/searchweather.zip
kind: ArchiveUploadSpec
name: backend-searchweather-zip-f63U

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: searchweather
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-searchweather-zip-f63U
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T04:12:42Z"
